/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vlak.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vlak.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube161.geometry} material={nodes.Cube161.material} position={[-1.208, 0.349, 27.16]} rotation={[-Math.PI, 1.567, -Math.PI]} scale={[2.992, 0.265, 0.326]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.001']} position={[-2.859, 5.732, 48.894]} scale={[2.12, 1, 14.725]} />
    </group>
  )
}

useGLTF.preload('/vlak.gltf')
