/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vozidla.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vozidla.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.063, 0.914, -4.484]} scale={[4.947, 0.732, 1.438]}>
        <mesh geometry={nodes.Cube120.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube120_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube120_2.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube120_3.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube120_4.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube120_5.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube120_6.geometry} material={materials['Material_1.005']} />
        <mesh geometry={nodes.Cube120_7.geometry} material={materials['Material_1.008']} />
      </group>
      <group position={[-20.83, 3.174, 1.338]} rotation={[0, 0, 0.22]} scale={[2.015, 1.138, 1.455]}>
        <mesh geometry={nodes.Cube152.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube152_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube152_2.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube152_3.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube152_4.geometry} material={materials['Material_1.012']} />
        <mesh geometry={nodes.Cube152_5.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube152_6.geometry} material={materials['Material_1.013']} />
        <mesh geometry={nodes.Cube152_7.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube152_8.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube152_9.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube152_10.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cube152_11.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube152_12.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Cube152_13.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Cube152_14.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Cube152_15.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Cube152_16.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Cube152_17.geometry} material={materials['Material.033']} />
        <mesh geometry={nodes.Cube152_18.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Cube152_19.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Cube152_20.geometry} material={materials['Material.036']} />
        <mesh geometry={nodes.Cube152_21.geometry} material={materials['Material.037']} />
        <mesh geometry={nodes.Cube152_22.geometry} material={materials['Material.038']} />
        <mesh geometry={nodes.Cube152_23.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Cube152_24.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.Cube152_25.geometry} material={materials['Material.041']} />
        <mesh geometry={nodes.Cube152_26.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Cube152_27.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Cube152_28.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube152_29.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube152_30.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Cube152_31.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.Cube152_32.geometry} material={materials['Material.048']} />
        <mesh geometry={nodes.Cube152_33.geometry} material={materials['Material.049']} />
        <mesh geometry={nodes.Cube152_34.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Cube152_35.geometry} material={materials['Material.051']} />
        <mesh geometry={nodes.Cube152_36.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Cube152_37.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube152_38.geometry} material={materials['Material.054']} />
        <mesh geometry={nodes.Cube152_39.geometry} material={materials['Material.055']} />
      </group>
      <group position={[-1.71, 2.966, 7.766]} rotation={[2.792, 0, 0]} scale={[0.447, 0.183, 0.031]}>
        <mesh geometry={nodes.Cube269.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube269_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube269_2.geometry} material={materials['Material_1.001']} />
        <mesh geometry={nodes.Cube269_3.geometry} material={materials['Material.064']} />
        <mesh geometry={nodes.Cube269_4.geometry} material={materials['Material.065']} />
        <mesh geometry={nodes.Cube269_5.geometry} material={materials['Material_1.002']} />
        <mesh geometry={nodes.Cube269_6.geometry} material={materials['Material.101']} />
        <mesh geometry={nodes.Cube269_7.geometry} material={materials['Material.100']} />
        <mesh geometry={nodes.Cube269_8.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube269_9.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube269_10.geometry} material={materials['Material.104']} />
        <mesh geometry={nodes.Cube269_11.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube269_12.geometry} material={materials['Material.107']} />
      </group>
    </group>
  )
}

useGLTF.preload('/vozidla.gltf')
